# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VV(object):
    def setupUi(self, VV):
        VV.setObjectName("VV")
        VV.resize(1067, 673)
        self.tabWidget = QtWidgets.QTabWidget(VV)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 671))
        self.tabWidget.setObjectName("tabWidget")
        self.VV_2 = QtWidgets.QWidget()
        self.VV_2.setObjectName("VV_2")
        self.DCTpreview = QtWidgets.QLabel(self.VV_2)
        self.DCTpreview.setGeometry(QtCore.QRect(10, 10, 1031, 621))
        self.DCTpreview.setText("")
        self.DCTpreview.setScaledContents(True)
        self.DCTpreview.setObjectName("DCTpreview")
        self.exit = QtWidgets.QPushButton(self.VV_2)
        self.exit.setGeometry(QtCore.QRect(940, 600, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(204, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.exit.setObjectName("exit")
        self.tabWidget.addTab(self.VV_2, "")

        # self.Objects = QtWidgets.QWidget()
        # self.Objects.setObjectName("Objects")
        # self.detected_objects = QtWidgets.QLabel(self.Objects)
        # self.detected_objects.setGeometry(QtCore.QRect(10, 10, 751, 441))
        # self.detected_objects.setText("")
        # self.detected_objects.setObjectName("detected_objects")
        # self.tabWidget.addTab(self.Objects, "")
        # self.tab = QtWidgets.QWidget()
        # self.tab.setObjectName("tab")
        # self.logs = QtWidgets.QScrollArea(self.tab)
        # self.logs.setGeometry(QtCore.QRect(0, 0, 1051, 631))
        # self.logs.setWidgetResizable(True)
        # self.logs.setObjectName("logs")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1049, 629))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.logs.setWidget(self.scrollAreaWidgetContents)
        # self.tabWidget.addTab(self.tab, "")
        # self.tab_2 = QtWidgets.QWidget()
        # self.tab_2.setObjectName("tab_2")
        # self.graph = QtWidgets.QGraphicsView(self.tab_2)
        # self.graph.setGeometry(QtCore.QRect(10, 10, 1041, 621))
        # self.graph.setObjectName("graph")
        # self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(VV)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VV)

    def retranslateUi(self, VV):
        _translate = QtCore.QCoreApplication.translate
        VV.setWindowTitle(_translate("VV", "Voice Assistance For Visually Impaired Person"))
        self.exit.setText(_translate("VV", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VV_2), _translate("VV", "V.V"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.Objects), _translate("VV", "Objects"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("VV", "Logs"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("VV", "Statistics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VV = QtWidgets.QDialog()
    ui = Ui_VV()
    ui.setupUi(VV)
    VV.show()
    sys.exit(app.exec_())
